name: Update Open Data Protal Access By Category Dataset

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 0' # runs every Sunday at 1 AM in PDT time zone

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sodapy socrata-py~=1.1.0
        pip install azure-storage-blob

    - name: Set up Git user
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "github-actions-bot@users.noreply.github.com"

    - name: Run Python script
      env:
        MY_SOCRATA_USERNAME: ${{ secrets.MY_SOCRATA_USERNAME }}
        MY_SOCRATA_PASSWORD: ${{ secrets.MY_SOCRATA_PASSWORD }}
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}
        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      run: |
        python "${{ github.workspace }}/openDataProtalByAccessCategory.py"
